/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NuqsRouteImport } from './routes/nuqs'
import { Route as IndexRouteImport } from './routes/index'

const NuqsRoute = NuqsRouteImport.update({
  id: '/nuqs',
  path: '/nuqs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nuqs': typeof NuqsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nuqs': typeof NuqsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nuqs': typeof NuqsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nuqs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nuqs'
  id: '__root__' | '/' | '/nuqs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NuqsRoute: typeof NuqsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nuqs': {
      id: '/nuqs'
      path: '/nuqs'
      fullPath: '/nuqs'
      preLoaderRoute: typeof NuqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NuqsRoute: NuqsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
